// Generated by gencpp from file BCI/BoolStateBCI.msg
// DO NOT EDIT!


#ifndef BCI_MESSAGE_BOOLSTATEBCI_H
#define BCI_MESSAGE_BOOLSTATEBCI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace BCI
{
template <class ContainerAllocator>
struct BoolStateBCI_
{
  typedef BoolStateBCI_<ContainerAllocator> Type;

  BoolStateBCI_()
    : data(false)  {
    }
  BoolStateBCI_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::BCI::BoolStateBCI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BCI::BoolStateBCI_<ContainerAllocator> const> ConstPtr;

}; // struct BoolStateBCI_

typedef ::BCI::BoolStateBCI_<std::allocator<void> > BoolStateBCI;

typedef boost::shared_ptr< ::BCI::BoolStateBCI > BoolStateBCIPtr;
typedef boost::shared_ptr< ::BCI::BoolStateBCI const> BoolStateBCIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::BCI::BoolStateBCI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::BCI::BoolStateBCI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::BCI::BoolStateBCI_<ContainerAllocator1> & lhs, const ::BCI::BoolStateBCI_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::BCI::BoolStateBCI_<ContainerAllocator1> & lhs, const ::BCI::BoolStateBCI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace BCI

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::BCI::BoolStateBCI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::BCI::BoolStateBCI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BCI::BoolStateBCI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::BCI::BoolStateBCI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BCI::BoolStateBCI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::BCI::BoolStateBCI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::BCI::BoolStateBCI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::BCI::BoolStateBCI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::BCI::BoolStateBCI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BCI/BoolStateBCI";
  }

  static const char* value(const ::BCI::BoolStateBCI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::BCI::BoolStateBCI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
;
  }

  static const char* value(const ::BCI::BoolStateBCI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::BCI::BoolStateBCI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolStateBCI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BCI::BoolStateBCI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::BCI::BoolStateBCI_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BCI_MESSAGE_BOOLSTATEBCI_H
