// Generated by gencpp from file Eyetracking/BoolStateEyetracking.msg
// DO NOT EDIT!


#ifndef EYETRACKING_MESSAGE_BOOLSTATEEYETRACKING_H
#define EYETRACKING_MESSAGE_BOOLSTATEEYETRACKING_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Eyetracking
{
template <class ContainerAllocator>
struct BoolStateEyetracking_
{
  typedef BoolStateEyetracking_<ContainerAllocator> Type;

  BoolStateEyetracking_()
    : bool_data(false)
    , int_data(0)  {
    }
  BoolStateEyetracking_(const ContainerAllocator& _alloc)
    : bool_data(false)
    , int_data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _bool_data_type;
  _bool_data_type bool_data;

   typedef int32_t _int_data_type;
  _int_data_type int_data;





  typedef boost::shared_ptr< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> const> ConstPtr;

}; // struct BoolStateEyetracking_

typedef ::Eyetracking::BoolStateEyetracking_<std::allocator<void> > BoolStateEyetracking;

typedef boost::shared_ptr< ::Eyetracking::BoolStateEyetracking > BoolStateEyetrackingPtr;
typedef boost::shared_ptr< ::Eyetracking::BoolStateEyetracking const> BoolStateEyetrackingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator1> & lhs, const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator2> & rhs)
{
  return lhs.bool_data == rhs.bool_data &&
    lhs.int_data == rhs.int_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator1> & lhs, const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Eyetracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7718df7148bc03e28cca1a6761586382";
  }

  static const char* value(const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7718df7148bc03e2ULL;
  static const uint64_t static_value2 = 0x8cca1a6761586382ULL;
};

template<class ContainerAllocator>
struct DataType< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Eyetracking/BoolStateEyetracking";
  }

  static const char* value(const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool bool_data\n"
"int32 int_data\n"
;
  }

  static const char* value(const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bool_data);
      stream.next(m.int_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoolStateEyetracking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Eyetracking::BoolStateEyetracking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Eyetracking::BoolStateEyetracking_<ContainerAllocator>& v)
  {
    s << indent << "bool_data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bool_data);
    s << indent << "int_data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.int_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EYETRACKING_MESSAGE_BOOLSTATEEYETRACKING_H
